# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 782b7ae49eda9f524f3a8c7f41901c69f721ecc860f4b786aa472f2959dca23b3d559cce69ed45da16aa85cbbc073e0088f7fc56c463d9a952ce36726d6e7eba

test:
  secret_key_base: 3ce032695014f9ca4b1707192ebbe6e78f4c6e8b41188df9d2e64a30f4297cd3319cb1196908a8aacbfb5d6c989a051634475f2637b41a69e2bf22604f6cafc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
